ensure_real_tab()
new_tab("https://www.alchemy.com/faucets/ethereum-sepolia")
wait_for_load(15)
print("=== TITLE ===")
print(js("document.title"))
print("=== PAGE TEXT (first 2000 chars) ===")
print(js("document.body.innerText.substring(0, 2000)"))
print("=== INPUTS ===")
inputs = js("Array.from(document.querySelectorAll('input, textarea')).map(function(el, i) { return { idx: i, placeholder: el.placeholder, type: el.type, id: el.id, name: el.name }; })")
print(str(inputs))
print("=== BUTTONS ===")
buttons = js("Array.from(document.querySelectorAll('button')).map(function(el, i) { return { idx: i, text: el.innerText.substring(0, 40), class: el.className.substring(0, 60) }; })")
print(str(buttons))
capture_screenshot("/tmp/alchemy_page.png")
print("Screenshot saved")
